# Generated by Django 2.1.5 on 2020-09-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0006_auto_20200925_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
