# Generated by Django 2.1.5 on 2020-09-27 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0007_auto_20200925_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='eventuser',
        ),
        migrations.RemoveField(
            model_name='event',
            name='timeperiod',
        ),
        migrations.AddField(
            model_name='event',
            name='end',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='start',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
