# Generated by Django 2.1.5 on 2020-09-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0008_auto_20200927_0258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
