# Generated by Django 2.1.5 on 2020-10-07 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0009_auto_20200928_0645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='start',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='end',
            new_name='time',
        ),
    ]
