# Generated by Django 2.1.5 on 2020-10-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0010_auto_20201007_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='room',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
